// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP0wPhpRMHfsP_JMV3XgaMz5_e7gJcbD4',
    appId: '1:32499502256:web:b528c48b6e11aa0d707f75',
    messagingSenderId: '32499502256',
    projectId: 'tutfinder-addb6',
    authDomain: 'tutfinder-addb6.firebaseapp.com',
    storageBucket: 'tutfinder-addb6.appspot.com',
    measurementId: 'G-67N7BXET03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb4aSQYMDsW2zcclYDZeHzdgbArRZm1Z8',
    appId: '1:32499502256:android:b8eb9de384b48bea707f75',
    messagingSenderId: '32499502256',
    projectId: 'tutfinder-addb6',
    storageBucket: 'tutfinder-addb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajTlPvMnD4nZeTc3D2Ttzrueswt1GjC0',
    appId: '1:32499502256:ios:941bc171637ecbc2707f75',
    messagingSenderId: '32499502256',
    projectId: 'tutfinder-addb6',
    storageBucket: 'tutfinder-addb6.appspot.com',
    iosClientId: '32499502256-u71socird1f67hltpb5urp7kdpidt28c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajTlPvMnD4nZeTc3D2Ttzrueswt1GjC0',
    appId: '1:32499502256:ios:20483a4271e66c0c707f75',
    messagingSenderId: '32499502256',
    projectId: 'tutfinder-addb6',
    storageBucket: 'tutfinder-addb6.appspot.com',
    iosClientId: '32499502256-fn2vum4cdlroonr65i4l8hj7u54gno6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutfinder.RunnerTests',
  );
}
